name: documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'common/docs/**'
      - '.github/workflows/docs.yml'
      - 'README.rst'
  pull_request:
    branches: [ main ]
    paths:
      - 'common/docs/**'
      - '.github/workflows/docs.yml'
      - 'README.rst'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  check_repo:
    runs-on: ubuntu-latest
    outputs:
      is_main_repo: ${{ steps.check.outputs.is_main_repo }}
    steps:
      - id: check
        run: |
          if [[ "$GITHUB_REPOSITORY" == "kakwa/pakste" ]]; then
            echo "is_main_repo=true" >> $GITHUB_OUTPUT
          else
            echo "is_main_repo=false" >> $GITHUB_OUTPUT
          fi
          echo "Repository: $GITHUB_REPOSITORY"

  build:
    needs: check_repo
    if: github.ref == 'refs/heads/main' && needs.check_repo.outputs.is_main_repo == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme
          if [ -f common/docs/requirements.txt ]; then
            pip install -r common/docs/requirements.txt
          fi

      - name: Build documentation
        run: make html -C common/docs

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./common/docs/_build/html
